version: '3.2'
services:
  database:
    container_name: directus_database
    image: mysql:8.0.18
    networks:
      - directus
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=d1r3ctu5
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.24
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'd1r3ctu5'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@test.com'
      ADMIN_PASSWORD: '4dm1n'

      CORS_ORIGIN: 'true'
      CORS_CREDENTIALS: 'true'
    restart: on-failure

networks:
  directus:
    name: directus_network
    ipam:
      driver: default
      config:
        - subnet: 172.64.5.0/28
